## This script details one way to process datas generated by cytofkit package on CyTOF data

#### Set wd and useful packages ---------------------------------------------------------------
setwd(".")
library(ggplot2)
library(RColorBrewer)
library(scales)
library(dplyr)
library(rio)
library(stringr)
library(pheatmap)

brewer.set <- "Set1"
brewer.colours.treated <- brewer_pal(palette = brewer.set)(5)[c(5,1)]
brewer.colours.3colors <- brewer_pal(palette = brewer.set)(3)[c(1,2,3)]
seq.brew <- brewer_pal(type = "seq", palette = 16)(9)

font_family="Helvetica"
font.size <- 12

#### After running cytokit function, 
## Option 1 is to explore generated data using the cytofShinyAPP 
l=load("cytofkit_Project1.RData")
str(analysis_results)
#cytofkitShinyAPP()

## Option 2 is to process generated data with this script, and adapt it to you own needs

# As a first step, we will evaluate clusters proportion, their differences among compared groups, and plot
# Transpose cytofkit_Project1_Rphenograph_cluster_cell_percentage.csv and add "Cluster" to first column
Table = read.csv("cytofkit_Project1_Rphenograph_cluster_cell_percentage.csv", sep=";", header=TRUE, stringsAsFactors = F)
str(Table)
Table$Group=as.factor(Table$Group)
attach(Table)
# You can plot proportions of each cluster in each group using the code below
#Sample and Group are first two columns
var=colnames(Table)[3:ncol(Table)]
for (variable in var) {
  a <- ggplot(data=Table, aes(x=Group, y=get(variable), fill=Group))
  a <- a + geom_boxplot(colour="black", width=0.3, fatten=1, alpha=0.6, size=0.8, outlier.shape=NA)
  a <- a + geom_jitter(width=0.1, size=3, alpha=1)
  a <- a + scale_fill_manual(values = brewer.colours.treated)
  a <- a + theme_bw()
  a <- a + ylab(paste0("%", variable))
  a <- a + theme(legend.title=element_blank()) 
  a <- a + theme(legend.position="none")
  a <- a + theme(axis.text=element_text(size=12, face="bold"), axis.text.x=element_text(vjust=2, size=12, face="bold"))
  a <- a + theme(panel.border = element_rect(linetype = "solid", size=1, colour = "black"))
  a <- a + theme(axis.title=element_text(size=12, face="bold"),axis.ticks=element_line(size=1))
  a
  ggsave(filename=paste0(variable, ".pdf"), plot=a, device="pdf", path=file.path(".", "Plots"), width=5, height=3)
}
# You can evaluate the mean or other statistical parameters using
#Table %>% group_by(Group) %>% summarise(mean(cluster_2))
# You can evaluate the significance of individual clusters among groups using the regression code below

#l=lm(data=Table, cluster_11 ~ Group)
#summary(l)

# You can evaluate the significance among all groups using the loop below
ClusterModelEstimates=data.frame(Cluster=NA,Estimate=NA,pvalue=NA)
for(i in 3:ncol(Table)){
  Table_sub=Table[,c(2,i)]
  colnames(Table_sub)=c("Group","Cluster")
  l=lm(data=Table_sub, Cluster ~ Group)
 tmp_df=data.frame(Cluster=colnames(Table)[i],Estimate=summary(l)$coefficients[2,c(1)],pvalue=summary(l)$coefficients[2,c(4)])
 ClusterModelEstimates=rbind(ClusterModelEstimates,tmp_df)
}
ClusterModelEstimates=na.omit(ClusterModelEstimates)

# You can export a table with P-values and estimates for all clusters
export(ClusterModelEstimates, "ClusterModelEstimates.csv")
# or for significant clusters
ClusterModelEstimates_sig=ClusterModelEstimates[ClusterModelEstimates$pvalue<0.1,]
export(ClusterModelEstimates_sig, "ClusterModelEstimates_sig.csv")

# You can create a heatmap of proportions of significant clusters
rownames(Table)=Table$SUBJID
anno_rows=data.frame(Table[,2])
rownames(anno_rows)=rownames(Table)
colnames(anno_rows)="Group"
pheatmap(Table[,ClusterModelEstimates_sig$Cluster],scale = "row",annotation_row = anno_rows,main = "Signficant Cluster percentages between Groups",cellwidth = 20,cellheight = 20)

## As a second step, we will investigate the composition of each cluster in term of expression of the markers used in our unbiased analysis
# Transpose cytofkit_Project1_Rphenograph_cluster_median_data.csv and add "Marker" to first column
# Calulate the mean for each marker accross all clusters, and normalize each column with the mean 
# Copy normalized data to a new csv file entitled "cytofkit_Project1_Rphenograph_cluster_median_data_norm.csv"
Pheno = read.csv("cytofkit_Project1_Rphenograph_cluster_median_data_norm.csv", sep=",", header=TRUE, stringsAsFactors = TRUE)
Pheno$Marker=as.factor(Pheno$Marker)
str(Pheno)
# One way to plot it is to generate a graph of markers expression per each cluster
for(i in 1:ncol(Pheno)){
  plt = ggplot(Pheno, aes(x = reorder(Marker, Pheno[,i]), y=Pheno[,i]))
  plt = plt + geom_bar(stat="identity")+ ggtitle(names(Pheno)[i])
  plt = plt + coord_flip() + xlab("Marker") + theme_bw()
  plt = plt + theme(plot.title=element_text(size=font.size, face="plain"), panel.grid.major = element_line(colour = "gray80"), axis.text =element_text(size = font.size, face="plain"), axis.title = element_text(size =font.size, face="plain"), legend.title = element_text(size = font.size, face="plain"))
  plt = plt + ylab("Intensity")
  plt
  ggsave(paste0("Plot per cluster",names(Pheno)[i], ".pdf"), path=file.path(".", "Plots"), plt, width = 5, height = 5)
}
# The other way is to generate a heatmap
#Pheno = read.csv("cytofkit_Project1_Rphenograph_cluster_median_data_norm.csv", sep=",", header=TRUE, stringsAsFactors = TRUE)
rownames(Pheno)=Pheno$Marker
Pheno$Marker=NULL

# You can then generate a heatmap on all clusters
pheatmap(mat = Pheno, color=seq.brew, ascale = "row", cluster_rows = TRUE, cluster_cols = F, filename = "./file.pdf", width = 10, height = 5)
# Or - recommended - you can generate the heatmap on selected significant clusters
# Annotate the columns first
Pheno_sig=Pheno[,c(paste0("cluster_",c(2,13,17,27,28)))]
annotation_c = as.data.frame(t(Pheno_sig[1,]))
d=rownames(annotation_c)
annotation_c <- as.data.frame(append(annotation_c, "NS", after = 2))
annotation_c <- data.frame(annotation_c[,c(2)])
rownames(annotation_c)=d
colnames(annotation_c)<- "Treated_vs_Control"
levels(annotation_c$Treated_vs_Control) <- c(levels(annotation_c$Treated_vs_Control),"Up", "Down")
# Identify each significant cluster and indicate direction of the effect (up or down as compared to ref group = pos or neg estimate)
annotation_c["cluster_2",1] <- c("Down")
annotation_c["cluster_13",1] <- c("Up")
annotation_c["cluster_17",1] <- c("Up")
annotation_c["cluster_27",1] <- c("Down")
annotation_c["cluster_28",1] <- c("Down")
Treated_vs_Control       <- brewer_pal(palette = brewer.set)(8)[c(4,8)]
names(Treated_vs_Control) <- c("Up", "Down")
anno_colors <- list(Treated_vs_Control = Treated_vs_Control)

pheatmap(mat = Pheno_sig, fontsize=7, annotation_col = annotation_c, annotation_colors = anno_colors, color=seq.brew, scale = "row", cluster_rows = TRUE, cluster_cols = TRUE,  filename = "./file.pdf", width = 6, height = 5)
